### ISSUE TITLE
Ifixit EN scraping error

### ISSUE THREAD

**Issue by kelson42** [openzim/ifixit#104] opened 2024-03-25 05:10 UTC
```
  File "/usr/local/lib/python3.8/site-packages/ifixit2zim-0.2.4-py3.8.egg/ifixit2zim/scraper_generic.py", line 94, in scrape_one_item
    self.process_one_item(item_key, item_data, item_content)
  File "/usr/local/lib/python3.8/site-packages/ifixit2zim-0.2.4-py3.8.egg/ifixit2zim/scraper_info.py", line 115, in process_one_item
    Global.add_html_item(
  File "/usr/local/lib/python3.8/site-packages/ifixit2zim-0.2.4-py3.8.egg/ifixit2zim/shared.py", line 435, in add_html_item
    Global.creator.add_item_for(
  File "/usr/local/lib/python3.8/site-packages/zimscraperlib/zim/creator.py", line 181, in add_item_for
    self.add_item(StaticItem(**kwargs), callback)
  File "/usr/local/lib/python3.8/site-packages/zimscraperlib/zim/creator.py", line 200, in add_item
    super().add_item(item)
  File "libzim/libzim.pyx", line 322, in libzim._Creator.add_item
RuntimeError: Impossible to add C/Info/Core_Returns
  dirent's title to add is : Core Returns
  existing dirent's title is : Core Returns

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ifixit2zim-0.2.4-py3.8.egg/ifixit2zim/scraper_generic.py", line 116, in scrape_items
    self.scrape_one_item(item_key, item_data)
  File "/usr/local/lib/python3.8/site-packages/ifixit2zim-0.2.4-py3.8.egg/ifixit2zim/scraper_generic.py", line 94, in scrape_one_item
    self.process_one_item(item_key, item_data, item_content)
  File "/usr/local/lib/python3.8/site-packages/ifixit2zim-0.2.4-py3.8.egg/ifixit2zim/scraper_info.py", line 115, in process_one_item
    Global.add_html_item(
  File "/usr/local/lib/python3.8/site-packages/ifixit2zim-0.2.4-py3.8.egg/ifixit2zim/shared.py", line 435, in add_html_item
    Global.creator.add_item_for(
  File "/usr/local/lib/python3.8/site-packages/zimscraperlib/zim/creator.py", line 181, in add_item_for
    self.add_item(StaticItem(**kwargs), callback)
  File "/usr/local/lib/python3.8/site-packages/zimscraperlib/zim/creator.py", line 200, in add_item
    super().add_item(item)
  File "libzim/libzim.pyx", line 322, in libzim._Creator.add_item
RuntimeError: Impossible to add C/about-us
  dirent's title to add is : About iFixit
  existing dirent's title is : About

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ifixit2zim-0.2.4-py3.8.egg/ifixit2zim/scraper_generic.py", line 116, in scrape_items
    self.scrape_one_item(item_key, item_data)
  File "/usr/local/lib/python3.8/site-packages/ifixit2zim-0.2.4-py3.8.egg/ifixit2zim/scraper_generic.py", line 94, in scrape_one_item
    self.process_one_item(item_key, item_data, item_content)
  File "/usr/local/lib/python3.8/site-packages/ifixit2zim-0.2.4-py3.8.egg/ifixit2zim/scraper_info.py", line 115, in process_one_item
    Global.add_html_item(
  File "/usr/local/lib/python3.8/site-packages/ifixit2zim-0.2.4-py3.8.egg/ifixit2zim/shared.py", line 435, in add_html_item
    Global.creator.add_item_for(
  File "/usr/local/lib/python3.8/site-packages/zimscraperlib/zim/creator.py", line 181, in add_item_for
    self.add_item(StaticItem(**kwargs), callback)
  File "/usr/local/lib/python3.8/site-packages/zimscraperlib/zim/creator.py", line 200, in add_item
    super().add_item(item)
  File "libzim/libzim.pyx", line 322, in libzim._Creator.add_item
RuntimeError: Impossible to add C/Info/Teardown
  dirent's title to add is : Guidelines for creating a Teardown
  existing dirent's title is : Gadget Teardowns

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ifixit2zim-0.2.4-py3.8.egg/ifixit2zim/scraper_generic.py", line 116, in scrape_items
    self.scrape_one_item(item_key, item_data)
  File "/usr/local/lib/python3.8/site-packages/ifixit2zim-0.2.4-py3.8.egg/ifixit2zim/scraper_generic.py", line 94, in scrape_one_item
    self.process_one_item(item_key, item_data, item_content)
  File "/usr/local/lib/python3.8/site-packages/ifixit2zim-0.2.4-py3.8.egg/ifixit2zim/scraper_info.py", line 115, in process_one_item
    Global.add_html_item(
  File "/usr/local/lib/python3.8/site-packages/ifixit2zim-0.2.4-py3.8.egg/ifixit2zim/shared.py", line 435, in add_html_item
    Global.creator.add_item_for(
  File "/usr/local/lib/python3.8/site-packages/zimscraperlib/zim/creator.py", line 181, in add_item_for
    self.add_item(StaticItem(**kwargs), callback)
  File "/usr/local/lib/python3.8/site-packages/zimscraperlib/zim/creator.py", line 200, in add_item
    super().add_item(item)
  File "libzim/libzim.pyx", line 322, in libzim._Creator.add_item
RuntimeError: Impossible to add C/about-us
  dirent's title to add is : Do-It-Yourself Repair
  existing dirent's title is : About

Exception ignored in: <function MagicDetect.__del__ at 0x7ff8006720d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/magic.py", line 308, in __del__
  File "/usr/local/lib/python3.8/site-packages/magic.py", line 135, in close
TypeError: 'NoneType' object is not callable

```

**Comment by benoit74** [comment] 2024-03-25 07:21
Duplicate of https://github.com/openzim/ifixit/issues/93

**Closed** 2024-03-25 07:21 UTC
Labels: bug
